version: '3'

services:
  # Postrgesql container
  spa-db:
    image: postgres:14.3
    container_name: ${SPA_DB_DATABASE}
    ports:
      - ${SPA_DB_PORT}:5432
    environment:
      POSTGRES_PASSSWORD: ${SPA_DB_PASSWORD}
      POSTGRES_DB: ${SPA_DB_DATABASE}
      POSTGRES_USER: ${SPA_DB_USERNAME}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./postgres:/var/lib/postgresql/data
